### ISSUE TITLE
launching with error

### ISSUE THREAD

**Issue by lalamax3d** [cgwire/kitsu-publisher#55]
Hi, 
i have installed latest version as per installation docs yesterday. using ubuntu 20. everything installed perfectly. installed in blender (2.83) as well.
opening desktop version and blender version both giving same error.
LOG is
```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.

=== An error occured !=== 
Error message:
Traceback (most recent call last):
  File "/home/user/.virtualenvs/kitsu/lib/python3.7/site-packages/kitsupublisher/views/MainWindow.py", line 118, in run
    self.function(*self.args, **self.kwargs)
  File "/home/user/.virtualenvs/kitsu/lib/python3.7/site-packages/kitsupublisher/views/MainWindow.py", line 79, in set_up_thread_listeners
    create_event(events, self.table_updated)
  File "/home/user/.virtualenvs/kitsu/lib/python3.7/site-packages/kitsupublisher/utils/connection.py", line 60, in create_event
    event_client = gazu.events.init()
  File "/home/user/.virtualenvs/kitsu/lib/python3.7/site-packages/gazu/events.py", line 16, in init
    path = get_event_host(client)
  File "/home/user/.virtualenvs/kitsu/lib/python3.7/site-packages/gazu/__init__.py", line 50, in get_event_host
    return raw.get_event_host(client, client=client)
TypeError: get_event_host() got multiple values for argument 'client'

QObject::setParent: Cannot set parent, new parent is in a different thread
```
SCREENSHOT
![image](https://user-images.githubusercontent.com/567387/94621549-f65e7680-02c9-11eb-8ae2-0bffcd501c92.png)

**Comment by frankrousseau** [comment]
Hello. Thank you for reporting this bug. We are going to have a look at this.

**Comment by frankrousseau** [comment]
The problem should be fixed. Can you upgrade the Kitsu publisher and try again?

**Comment by lalamax3d** [comment]
Just did and it worked. Thanks @frankrousseau
